import {
  CollectionReference,
  type DocumentData,
  DocumentReference,
  DocumentSnapshot,
  FieldPath,
  FieldValue,
  Firestore,
  Query,
  QuerySnapshot,
  type SetOptions,
  Timestamp,
  Transaction,
  WriteBatch,
  getFirestore,
} from "firebase-admin/firestore";

export {
  CollectionReference,
  type DocumentData,
  DocumentReference,
  DocumentSnapshot,
  FieldPath,
  FieldValue,
  Firestore,
  Query,
  QuerySnapshot,
  type SetOptions,
  Timestamp,
  Transaction,
  WriteBatch as Batch,
  getFirestore,
};
