import {
  CollectionReference,
  DocumentReference,
  DocumentSnapshot,
  FieldPath,
  FieldValue,
  Firestore,
  Query,
  QuerySnapshot,
  Timestamp,
  Transaction,
  WriteBatch,
  addDoc,
  collection,
  collectionGroup,
  deleteField,
  doc,
  getFirestore,
  onSnapshot,
  runTransaction,
  serverTimestamp,
  setDoc,
  updateDoc,
  writeBatch,
} from "firebase/firestore";

export * from "@kthksgy/firebase-common/firestore";

export {
  CollectionReference,
  DocumentReference,
  DocumentSnapshot,
  FieldPath,
  FieldValue,
  Firestore,
  Query,
  QuerySnapshot,
  Timestamp,
  Transaction,
  WriteBatch,
  addDoc as addDocument,
  collection as createCollectionReference,
  collectionGroup as createCollectionGroupReference,
  deleteField as createDeleteMarkFieldValue,
  doc as createDocumentReference,
  getFirestore,
  onSnapshot as watchDocuments,
  runTransaction,
  serverTimestamp as createServerTimestampFieldValue,
  setDoc as setDocument,
  updateDoc as updateDocument,
  writeBatch as createWriteBatch,
};
