import {
  CollectionReference,
  DocumentReference,
  DocumentSnapshot,
  FieldPath,
  FieldValue,
  Firestore,
  Query,
  QuerySnapshot,
  type SetOptions,
  Timestamp,
  Transaction,
  type TransactionOptions,
  WriteBatch,
  addDoc,
  collection,
  collectionGroup,
  deleteField,
  doc,
  getFirestore,
  onSnapshot,
  runTransaction,
  serverTimestamp,
  setDoc,
  updateDoc,
  writeBatch,
} from "firebase/firestore";

export {
  CollectionReference,
  DocumentReference,
  DocumentSnapshot,
  FieldPath,
  FieldValue,
  Firestore,
  Query,
  QuerySnapshot,
  type SetOptions,
  Timestamp,
  Transaction,
  type TransactionOptions,
  WriteBatch as Batch,
  addDoc as addDocument,
  collection as createCollectionReference,
  collectionGroup as createCollectionGroupReference,
  deleteField as createDeleteMarkFieldValue,
  doc as createDocumentReference,
  getFirestore,
  onSnapshot as watchDocument,
  onSnapshot as watchDocuments,
  runTransaction,
  serverTimestamp as createServerTimestampFieldValue,
  setDoc as setDocument,
  updateDoc as updateDocument,
  writeBatch as createBatch,
};
